name: flutter_selectable_list
description: "A practical solution to streamline building and managing the state of selectable lists."
version: 0.0.6
repository: https://github.com/CHB61/flutter_selectable_list
issue_tracker: https://github.com/CHB61/flutter_selectable_list
documentation: https://github.com/CHB61/flutter_selectable_list
homepage: https://github.com/CHB61/flutter_selectable_list

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
