name: flutter_selectable_list
description: "A widget library that simplifies building selectable lists, and provides a variety of options to display them."
version: 0.0.2
repository: https://github.com/CHB61/flutter_selectable_list
issue_tracker: https://github.com/CHB61/flutter_selectable_list
documentation: https://github.com/CHB61/flutter_selectable_list
homepage: https://github.com/CHB61/flutter_selectable_list

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
